### ISSUE TITLE
Practica 6: Reconocimiento de Imágenes

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-octocat#2]
[Reconocimiento de imagenes.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-octocat/files/8601276/Reconocimiento.de.imagenes.pdf)

**Comment by Brendalp** [comment]
Calificación = 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
